# Generated by Django 5.1.5 on 2025-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
