# Generated by Django 5.1.5 on 2025-01-23 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_destination_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='lodging_type',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='individual_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='lodging',
            field=models.CharField(default='Hotel', max_length=50),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='food_type',
            field=models.CharField(default='Veg', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
