# Generated by Django 5.1.5 on 2025-01-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_travelplan_lodging_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='user',
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=50),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='lodging',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Lodge', 'Lodge'), ('Resort', 'Resort')], max_length=50),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
