# Generated by Django 5.1.5 on 2025-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_travelplan_user_alter_travelplan_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='pricing_segment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travel_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
