# Generated by Django 5.1.5 on 2025-01-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_travelplan_pricing_segment_travelplan_travel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_type',
            field=models.CharField(choices=[('Local', 'Local'), ('International', 'International')], default='Local', max_length=50),
        ),
    ]
