# Generated by Django 5.1.5 on 2025-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_destination_destination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='Longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
