# Generated by Django 5.1.5 on 2025-02-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('Price', models.FloatField(default=0.0)),
                ('Rating', models.FloatField(default=0.0)),
                ('TimeTaken', models.FloatField(default=0.0)),
                ('Remarks', models.TextField(default='')),
                ('DestinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('Price', models.FloatField(default=0.0)),
                ('Rating', models.FloatField(default=0.0)),
                ('TimeTaken', models.FloatField(default=0.0)),
                ('Remarks', models.TextField(default='')),
                ('DestinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('Price', models.FloatField(default=0.0)),
                ('Rating', models.FloatField(default=0.0)),
                ('Anemeties', models.TextField(default='')),
                ('Remarks', models.TextField(default='')),
                ('DestinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
            ],
        ),
    ]
