# Generated by Django 5.1.5 on 2025-02-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_airline_bus_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='DestinationID',
            new_name='destinationID',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='TimeTaken',
            new_name='timeTaken',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='DestinationID',
            new_name='destinationID',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='TimeTaken',
            new_name='timeTaken',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Anemeties',
            new_name='anemeties',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='DestinationID',
            new_name='destinationID',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='Name',
        ),
    ]
