# Generated by Django 5.1.5 on 2025-02-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_createdat_airline_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.FloatField(default=0.0)),
                ('optimizedCost', models.FloatField(default=0.0)),
                ('destinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
