# Generated by Django 5.1.5 on 2025-02-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_travelcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelcost',
            name='optimizedCost',
        ),
        migrations.RemoveField(
            model_name='travelcost',
            name='total_cost',
        ),
    ]
