# Generated by Django 5.1.5 on 2025-02-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_travelcost_optimizedcost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Name',
            new_name='name',
        ),
    ]
