# Generated by Django 5.1.5 on 2025-02-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_name_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
